# Generated by Django 4.2.1 on 2023-06-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Viajeros', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servicios',
        ),
        migrations.AddField(
            model_name='reservarestaurante',
            name='hora_reserva',
            field=models.TimeField(null=True),
        ),
    ]
