# Generated by Django 4.2.1 on 2023-06-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Viajeros', '0002_delete_servicios_reservarestaurante_hora_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaexcursion',
            name='hora_reserva',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='reservarestaurante',
            name='hora_reserva',
            field=models.CharField(null=True),
        ),
    ]
